#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs script

if grep -qs integrity-check /proc/cmdline
then
	cd /live/image
	md5sum -c md5sum.txt < /dev/tty8 > /dev/tty8
	reboot
	while :; do sleep 60; done
fi
