#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Setting timezone..."

# live-initramfs script

cp -f /root/usr/share/zoneinfo/UTC /root/etc/localtime

log_end_msg
