#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Configuring fstab..."

# live-initramfs script

FSTAB=/root/etc/fstab

cat > $FSTAB <<EOF
${UNIONTYPE} / ${UNIONTYPE} rw 0 0
tmpfs /tmp tmpfs nosuid,nodev 0 0
EOF

# disabled for now
#rm -f /root/etc/rcS.d/S*checkroot.sh

if [ "${NOFASTBOOT}" != "Yes" ]
then
	touch root/fastboot
fi

log_end_msg
