#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""
FSTAB=/root/etc/fstab

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

if [ -n "${NOFSTAB}" ]
then
	exit 0
fi

if [ -s ${FSTAB} ]
then
	log_begin_msg "Not touching preexisting fstab..."
else
	log_begin_msg "Configuring fstab..."

	cat >> ${FSTAB} <<-EOF
	# /etc/fstab: static file system information.
	#
	# <file system> <mount point>   <type>  <options>       <dump>  <pass>
	${UNIONTYPE} / ${UNIONTYPE} rw 0 0
	tmpfs /tmp tmpfs nosuid,nodev 0 0
	EOF
fi

# live-initramfs script


# disabled for now
#rm -f /root/etc/rcS.d/S*checkroot.sh

if [ "${NOFASTBOOT}" != "Yes" ]
then
	touch root/fastboot
fi

log_end_msg
