#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOXAUTOCONFIG}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Configuring X kludges..."

# live-initramfs script

if [ -n "$XVIDEOMODE" ]
then
	mount -n -o bind /sys /root/sys
	mount -n -o bind /proc /root/proc
	mount -n -o bind /dev /root/dev

chroot /root debconf-communicate -fnoninteractive live-initramfs > /dev/null << EOF
set xserver-xorg/config/monitor/mode-list ${XVIDEOMODE}
set xserver-xorg/config/display/modes ${XVIDEOMODE}
EOF

	chroot /root dexconf

	umount /root/sys
	umount /root/proc
	umount /root/dev
fi

log_end_msg
