#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOXAUTOCONFIG}" ]
then
	exit 0
fi

if [ ! -x /root/usr/bin/X ]
then
	exit 0
fi

[ -n "$XVIDEOMODE" ] || exit

. /scripts/live-functions

log_begin_msg "Configuring X video modes"

# live-initramfs script

. /live.vars

if [ "${XVIDEOMODE}" = "auto" ]
then
	rm -f /root/etc/X11/Xsession.d/21xvidemode

	exit 0
fi

if [ -x "$(which xrandr 2>/dev/null)" ]
then
	echo "xrandr -s ${XVIDEOMODE} || /bin/true" >> /root/etc/X11/Xsession.d/21xvidemode
fi

log_end_msg
