#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

# this bottom script currently only works with upstart
if [ ! -d /root/etc/init ]
then
	exit 0
fi

. /scripts/live-functions

# live-initramfs script

for ARGUMENT in $(cat /proc/cmdline)
do
	case ${ARGUMENT} in
		serialtty=*)
			tty="${ARGUMENT#serialtty=}"

			log_begin_msg "Setting up a serial tty..."

cat > /root/etc/init/${tty}.conf <<EOF
start on stopped rc RUNLEVEL=[2345]
stop on runlevel [!2345]

respawn
exec /sbin/getty -L 115200 ${tty} vt100
EOF

			log_end_msg
			;;
	esac
done
