#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Loading preseed file..."

# live-initramfs script

if [ -f "/root/${LOCATION}" ]; then
    chroot /root debconf-set-selections < "/root/${LOCATION}"
fi

if [ -n "${PRESEEDS}" ]; then
    for preseed in ${PRESEEDS}; do
       question="${preseed%%=*}"
               value="${preseed#*=}"
               live-preseed /root "${question}" "${value}"
       done
fi

log_end_msg

exit 0
