#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOPRESEED}" ]
then
	exit 0
fi

. /scripts/live-functions
load_confmodule

log_begin_msg "Loading preseed file"

# live-initramfs script

if [ -e /preseed.cfg ]
then
	live-set-selections /preseed.cfg
fi

if [ -n "${LOCATIONS}" ]
then
	for item in ${LOCATIONS}
	do
		live-set-selections "/root$item"
	done
fi

if [ -n "${PRESEEDS}" ]
then
	for preseed in ${PRESEEDS}
	do
		question="${preseed%%=*}"
		value="${preseed#*=}"

		live-preseed /root "${question}" "${value}"
	done
fi

if db_get preseed/early_command && [ "$RET" ]
then
	echo 'APT::Keep-Fds { "3"; "4"; };' > /root/etc/apt/apt.conf.d/00-early-debconf
	DEBIAN_FRONTEND=passthrough \
	DEBCONF_READFD=3 \
	DEBCONF_WRITEFD=4 \
	DEBCONF_DB_REPLACE=configdb \
	DEBCONF_DB_OVERRIDE='Pipe{infd:none outfd:none}' \
	sh -c "$RET"
	rm -f /root/etc/apt/apt.conf.d/00-early-debconf
fi

# Clear out debconf database backup files to save memory.
rm -f /root/var/cache/debconf/*.dat-old

log_end_msg

exit 0
