#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOACCESSIBILITY}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Configuring accessibility options..."

# live-initramfs script

gconf_version=$(chroot /root /usr/bin/dpkg-query -W --showformat='${Version}' gconf2 2>/dev/null) || gconf_version=""

gct ()
{
	if [ "${gconf_version}" ]
	then
		chroot /root sudo -u "${USERNAME}" gconftool-2 "${@}"
	fi
}

case ${ACCESS} in
	access=v1)
		# Lesser Visual Impairment
		gct -s -t string /desktop/gnome/interface/gtk_theme HighContrastLargePrint
		gct -s -t string /desktop/gnome/interface/icon_theme HighContrast
		gct -s -t string /desktop/gnome/interface/monospace_font_name "monospace 18"
		gct -s -t string /desktop/gnome/interface/font_name "sans 18"
		gct -s -t string /apps/metacity/general/theme Atlanta
		gct -s -t string /desktop/gnome/background/picture_filename ""
		gct -s -t string /desktop/gnome/background/picture_options none
		gct -s -t string /desktop/gnome/background/primary_color \#666666
		gct -s -t string /desktop/gnome/background/secondary_color \#7F7F7F
		gct -s -t string /desktop/gnome/background/color_shading_type solid
		gct -s -t int /desktop/gnome/peripherals/mouse/cursor_size 48
		gct -s -t string /desktop/gnome/peripherals/mouse/cursor_theme whiteglass
		;;

	access=v2)
		# Moderate Visual Impairment
		gct -s -t bool /desktop/gnome/interface/accessibility true
		gct -s -t bool /desktop/gnome/applications/at/visual/startup true
		gct -s -t bool /apps/gksu/disable-grab true

		if [ -e /root/usr/share/pycentral/gnome-orca/site-packages/orca/settings.py ]
		then
			sed -i '/^enableSpeech\W/ s/True/False/;/^enableMagnifier/ s/False/True/' /root/usr/share/pycentral/gnome-orca/site-packages/orca/settings.py
		fi
		;;

	access=v3)
		# Blindness
		# Disabled for now, until we know eSpeak works.
		#gct -s -t bool /desktop/gnome/sound/enable_esd false
		gct -s -t bool /desktop/gnome/interface/accessibility true
		gct -s -t bool /desktop/gnome/applications/at/visual/startup true
		gct -s -t bool /apps/gksu/disable-grab true
		;;

	braille=ask)
		# Braille
		gct -s -t bool /desktop/gnome/interface/accessibility true
		gct -s -t bool /desktop/gnome/applications/at/visual/startup true
		gct -s -t bool /apps/gksu/disable-grab true

		if [ -e /root/usr/share/pycentral/gnome-orca/site-packages/orca/settings.py ]
		then
			sed -i '/^enableSpeech\W/ s/True/False/;/^enableBraille/ s/False/True/' /root/usr/share/pycentral/gnome-orca/site-packages/orca/settings.py
		fi
		;;

	access=m1)
		# Minor Motor Difficulties
		gct -s -t bool /desktop/gnome/accessibility/keyboard/enable true
		gct -s -t bool /desktop/gnome/accessibility/keyboard/mousekeys_enable true
		gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_enable true
		gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_modifier_beep true
		gct -s -t bool /desktop/accessibility/gnome/keyboard/stickykeys_two_key_off false
		gct -s -t bool /desktop/gnome/peripherals/keyboard/repeat true
		gct -s -t int /desktop/gnome/peripherals/keyboard/delay 700
		gct -s -t int /desktop/gnome/peripherals/keyboard/rate 10
		gct -s -t bool /apps/gksu/disable-grab true

		if [ -e /root/etc/xdg/xfce4/mcs_settings/keyboard.xml ]
		then
			sed -i 's/0/1/' /root/etc/xdg/xfce4/mcs_settings/keyboard.xml
		fi
		;;

	access=m2)
		# Motor Difficulties - pointing devices
		gct -s -t bool /desktop/gnome/accessibility/keyboard/enable true
		gct -s -t bool /desktop/gnome/interface/accessibility true
		gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_enable true
		gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_modifier_beep false
		gct -s -t bool /desktop/accessibility/gnome/keyboard/stickykeys_two_key_off false
		gct -s -t list --list-type=string /desktop/gnome/accessibility/startup/exec_ats [onboard]

		if [ -e /root/etc/xdg/xfce4/mcs_settings/keyboard.xml ]
		then
			sed -i '/Sticky/ s/0/1/' /root/etc/xdg/xfce4/mcs_settings/keyboard.xml
		fi
		;;
esac

log_end_msg
