#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOPROGRAMCRASHES}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Enabling notifications about program crashes..."

# live-initramfs script

update_notifier_version=$(chroot /root dpkg-query -W --showformat='${Version}' update-notifier 2>/dev/null) || update_notifier_version=""

if [ -n "${update_notifier_version}" ]
then
	chroot /root sudo -u "${USERNAME}" gconftool-2 -t bool -s /apps/update-notifier/show_apport_crashes true
fi

log_end_msg
