#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Disabling kaboom"

# live-initramfs script

if [ -e /root/etc/kde4 ]
then
	mkdir -p /root/home/${USERNAME}/.local
	touch /root/home/${USERNAME}/.local/kaboom
fi

log_end_msg
