#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOKWALLET}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Disabling kwallet..."

# live-initramfs script

rm -f /root/usr/share/services/kded/kwalletd.desktop

log_end_msg
