#!/bin/sh

PREREQ=""

. /scripts/live-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

if [ -n "${NORESTRICTEDMANAGER}" ]
then
	exit 0
fi

log_begin_msg "Disabling restricted-manager..."

rm -f /root/etc/xdg/autostart/restricted-manager.desktop
rm -f /root/etc/xdg/autostart/restricted-manager-kde.desktop

log_end_msg
