#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

if [ -n "${NORESTRICTEDMANAGER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Disabling restricted-manager"

rm -f /root/etc/xdg/autostart/restricted-manager.desktop
rm -f /root/etc/xdg/autostart/restricted-manager-kde.desktop

# Since we disable restricted-manager, there isn't much point generating the
# fglrx or nvidia modules either. The other restricted modules may still be
# useful.
if [ -e /root/etc/default/linux-restricted-modules-common ]
then
	sed -i 's/^DISABLED_MODULES=""/DISABLED_MODULES="fglrx nv"/' \
		/root/etc/default/linux-restricted-modules-common
fi

log_end_msg
