#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Installing driver updates..."

# live-initramfs script

if [ ! -d /tmp/driver-updates ]; then
	exit 0
fi

install_dir=/var/cache/driver-updates

mkdir "/root$install_dir"
cp -a /tmp/driver-updates/*.deb "/root$install_dir/"

# We cannot leave packages in a bad state. So if the install fails, remove
# it. This will get caught in live.log.
for deb in "/root$install_dir"/*; do
	if ! chroot /root dpkg -i "$install_dir/$deb"; then
		chroot /root dpkg -P "${deb%%_*}"
	fi
done

log_end_msg
