#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Adding APT-CDROM source..."

# live-initramfs script

mkdir -p /root/cdrom
mount -n -o bind /cdrom /root/cdrom
chroot /root apt-cdrom -m add
umount /root/cdrom

log_end_msg
