#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOAPTCDROM}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Adding APT-CDROM source..."

# live-initramfs script

chroot /root apt-cdrom -m add

log_end_msg
