#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOAPPARMOR}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Disabling AppArmor (does not work with stacked file systems)..."

# live-initramfs script

chroot /root update-rc.d -f apparmor remove

log_end_msg
