#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Disabling AppArmor profile for Cups..."

# live-initramfs script

# workaround for AppArmor bug #131976

PROFILE=/root/etc/apparmor.d/usr.sbin.cupsd

if [ -e "$PROFILE" ]
then
	sed -i '/{/ s/{/flags=(complain) {/' $PROFILE
fi

log_end_msg
