#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Possibly disabling update-initramfs (useless on a live CD)..."

# live-initramfs script

chroot /root dpkg-divert --add --rename --quiet \
	/usr/sbin/update-initramfs

# Running off a USB disk or other writable media.
if [ -w /root/cdrom ] && \
   # rw is guaranteed to be first.
   grep -q ' /root/cdrom rw[, ]' /proc/self/mountinfo
then

cat > /root/usr/sbin/update-initramfs << 'EOF'
#!/bin/sh

set -e

update-initramfs.distrib "$@"

if [ -e /cdrom/live/initrd.lz ]
then
	zcat /initrd.img | lzma -9c >/cdrom/live/initrd.lz.new
	mv /cdrom/live/initrd.lz.new /cdrom/live/initrd.lz
else
	cp /initrd.img /cdrom/live/initrd.gz.new
	mv /cdrom/live/initrd.gz.new /cdrom/live/initrd.gz
fi

cp /vmlinuz /cdrom/live/vmlinuz.new
mv /cdrom/live/vmlinuz.new /cdrom/live/vmlinuz

exit 0
EOF

else

cat > /root/usr/sbin/update-initramfs << EOF
#!/bin/sh

echo "update-initramfs is disabled since running on read-only media"
exit 0
EOF

fi

chmod 0755 /root/usr/sbin/update-initramfs

log_end_msg
