#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -z "${HOOK}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Executing custom hook script..."

# live-initramfs script

cd /root
wget "${HOOK}"

./$(basename ${HOOK})

log_end_msg
