#!/bin/sh

# Checking depends
dpkg -l busybox file initramfs-tools sudo udev user-setup

# Checking recommends
dpkg -l eject loop-aes-utils uuid-runtime wget

# Checking suggests
dpkg -l curlftpfs genext2fs httpfs2 squashfs-tools mtd-tools

# Checking other packages
dpkg -l cryptsetup splashy usplash
