#!/bin/sh

# Error out in case a "wrong" file system was chosen.

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# FIXME: stop hardcoding overloading of initramfs-tools functions
. /scripts/functions
. /lib/live/boot/initramfs-tools.sh

if ! [ -d "/root/usr/share/live-boot" ]
then
	panic "A wrong rootfs was mounted."
fi
