#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""
FSTAB=/root/etc/fstab

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-boot header

# FIXME: stop hardcoding overloading of initramfs-tools functions
. /scripts/functions
. /lib/live/boot/initramfs-tools.sh

if [ -n "${NOFSTAB}" ]
then
	exit 0
fi

log_begin_msg "Configuring fstab"

# live-boot script

if ! grep -qs  "^${UNIONTYPE}" "${FSTAB}"
then
	echo "${UNIONTYPE} / ${UNIONTYPE} rw 0 0" >> "${FSTAB}"
fi

if ! grep -qs "^tmpfs /tmp" "${FSTAB}"
then
	echo "tmpfs /tmp tmpfs nosuid,nodev 0 0" >> "${FSTAB}"
fi

log_end_msg
