#!/bin/sh

PREREQ=""
DESCRIPTION="Copying config on real root fs..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

if [ -f /etc/casper.conf ] ; then 
	if [ ! -z "${CASPERCONF}" ]; then
		# Updating casper.conf
		sed -i -e 's/\(USERNAME="\).*"/\1'"${USERNAME}"'"/g' \
		    -e 's/\(USERFULLNAME="\).*"/\1'"${USERFULLNAME}"'"/g' \
		    -e 's/\(HOSTNAME="\).*"/\1'"${HOSTNAME}"'"/g' /etc/casper.conf
	fi
	cp -p /etc/casper.conf /root/etc/casper.conf

else
	cat <<EOF >/root/etc/casper.conf
export USERNAME="$USERNAME"
export USERFULLNAME="$USERFULLNAME"
export HOSTNAME="$HOSTNAME"
EOF

fi

