#!/bin/sh

PREREQ=""
DESCRIPTION="Moving mount points..."

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

# Move to the new root filesystem so that programs there can get at it.
mkdir -p /root/live_media
mount -n -o move /live_media /root/live_media

log_end_msg
