#!/bin/sh

PREREQ=""
DESCRIPTION="Moving mount points..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

# Move to the new root filesystem so that programs there can get at it.
if [ ! -d /root/live_media ]; then
    mkdir -p /root/live_media
    mount -n -o move /live_media /root/live_media
fi

log_end_msg
