#! /bin/sh

PREREQ=""
DESCRIPTION="Setting up locales..."

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

if [ -e /root/etc/default/locale ]; then
	grep_file=/root/etc/default/locale
	locale=$(grep 'LANG=' ${grep_file} | sed s/'LANG='// | tr -d '"' ) 
elif [ -e /root/etc/environment ]; then # Old locales policy
	grep_file=/root/etc/environment
fi

if [ -z "${grep_file}" ]; then 
	grep_file=/root/etc/default/locale
fi

# commandline
for x in $(cat /proc/cmdline); do
	case $x in
		debian-installer/locale=*)
			locale=${x#debian-installer/locale=}
			set_locale="true"
			;;
		locale=*)
			locale=${x#locale=}
			set_locale="true"
			;;
	esac
done

if [ -z "${locale}" ]; then
	# Set a default one
	locale=en_US.UTF-8
	set_locale="true"
fi

if [ "${set_locale}" ]; then
	LANG=$(grep "^${locale}" /root/usr/share/i18n/SUPPORTED | grep UTF-8 |sed -e 's, .*,,' -e q)
	printf 'LANG="%s"\n' "${LANG}" >> "${grep_file}"
	if [ "${BUILD_SYSTEM}" == "Debian" ]; then
		chroot /root /usr/sbin/locale-gen
	else
		chroot /root /usr/sbin/locale-gen "${LANG}"
	fi
fi

log_end_msg
