#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring gnome-panel-data..."

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

if chroot /root /bin/sh -c laptop-detect; then
    casper-reconfigure /root gnome-panel-data
fi

panel_version=$(chroot /root /usr/bin/dpkg-query -W --showformat='${Version}' gnome-panel-data 2>/dev/null) || panel_version=""
if [ -n "$panel_version" ]; then
    chroot /root su $USERNAME -- gconftool-2 -s -t bool /apps/panel/global/disable_lock_screen true
fi

log_end_msg
