#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring screensaver..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"


gnome_screensaver_version=$(chroot /root dpkg-query -W --showformat='${Version}' gnome-screensaver 2>/dev/null) || gnome_screensaver_version=""

if [ "${BUILD_SYSTEM}" == "Ubuntu" ]; then
	gnome_screensaver_lock="/apps/gnome-screensaver/lock"
else
	gnome_screensaver_lock="/apps/gnome-screensaver/lock_enabled"
fi
	
if [ -n "$gnome_screensaver_version" ]; then
    chroot /root sudo -u "$USERNAME" gconftool-2 -t bool -s "${gnome_screensaver_lock}" false
fi

log_end_msg
