#! /bin/sh

PREREQ=""
DESCRIPTION="Preconfiguring networking..."
IFFILE="/root/etc/network/interfaces"

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

cat > "$IFFILE" <<EOF
auto lo
iface lo inet loopback

EOF

udevtrigger -Bpci -Iclass="0x02*"

for interface in /sys/class/net/eth* /sys/class/net/ath* /sys/class/net/wlan*; do
    [ -e $interface ] || continue
    i="$(basename $interface)"
    cat >> "$IFFILE" <<EOF
auto $i
iface $i inet dhcp

EOF
done

for i in eth0 eth1 eth2 ath0 wlan0; do
    [ ! -e /sys/class/net/$i ] || continue
    cat >> "$IFFILE" <<EOF
auto $i
iface $i inet dhcp

EOF
done

log_end_msg
