#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring accessibility options..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

gconf_version=$(chroot /root /usr/bin/dpkg-query -W --showformat='${Version}' gconf2 2>/dev/null) || gconf_version=""

gct() {
    if [ "$gconf_version" ]; then
        chroot /root sudo -u "$USERNAME" gconftool-2 "$@"
    fi
}

kderc_addtoprefixes() {
    if [ -e "/root/etc/kderc" ]; then
        sed -i "s|\\(prefixes=/usr/share/kubuntu-default-settings/kde-profile/default/\\)|\\1,$1|" /root/etc/kderc
    fi
}

case ${ACCESS} in
    # Lesser Visual Impairment
    v1)
        gct -s -t string /desktop/gnome/interface/gtk_theme HighContrastLargePrint
        gct -s -t string /desktop/gnome/interface/icon_theme HighContrast
        gct -s -t string /desktop/gnome/interface/monospace_font_name "monospace 18"
        gct -s -t string /desktop/gnome/interface/font_name "sans 18"
        gct -s -t string /apps/metacity/general/theme Atlanta
        gct -s -t string /desktop/gnome/background/picture_filename ""
        gct -s -t string /desktop/gnome/background/picture_options none
        gct -s -t string /desktop/gnome/background/primary_color \#666666
        gct -s -t string /desktop/gnome/background/secondary_color \#7F7F7F
        gct -s -t string /desktop/gnome/background/color_shading_type solid
        gct -s -t int /desktop/gnome/peripherals/mouse/cursor_size 48
        gct -s -t string /desktop/gnome/peripherals/mouse/cursor_theme whiteglass

        kderc_addtoprefixes /usr/share/kubuntu-default-settings/kde-profile/lesser-visual-impairment/
        ;;
    # Moderate Visual Impairment
    v2)
        gct -s -t bool /desktop/gnome/interface/accessibility true
        gct -s -t list --list-type=string /desktop/gnome/accessibility/startup/exec_ats [orca]
        #gct -s -t bool /apps/gnopernicus/srcore/mag_active true
        #gct -s -t bool /apps/gnopernicus/srcore/sp_active false

        kderc_addtoprefixes /usr/share/kubuntu-default-settings/kde-profile/lesser-visual-impairment/,/usr/share/kubuntu-default-settings/kde-profile/moderate-visual-impairment/
        ;;
    # Blindness
    v3)
        gct -s -t bool /desktop/gnome/sound/enable_esd false
        gct -s -t bool /desktop/gnome/interface/accessibility true
        gct -s -t list --list-type=string /desktop/gnome/accessibility/startup/exec_ats [orca]
        #gct -s -t bool /apps/gnopernicus/srcore/sp_active true
        #gct -s -t bool /apps/gnopernicus/srcore/mag_active false
        ;;
        # Minor Motor Difficulties
    m1)
        gct -s -t bool /desktop/gnome/accessibility/keyboard/enable true
        gct -s -t bool /desktop/gnome/accessibility/keyboard/mousekeys_enable true
        gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_enable true
        gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_modifier_beep true
        gct -s -t bool /desktop/accessibility/gnome/keyboard/stickykeys_two_key_off false
        gct -s -t bool /desktop/gnome/peripherals/keyboard/repeat true
        gct -s -t int /desktop/gnome/peripherals/keyboard/delay 700
        gct -s -t int /desktop/gnome/peripherals/keyboard/rate 10

        kderc_addtoprefixes /usr/share/kubuntu-default-settings/kde-profile/minor-motor-difficulties/
        ;;
    # Motor Difficulties - pointing devices
    m2)
        gct -s -t bool /desktop/gnome/accessibility/keyboard/enable true
        gct -s -t bool /desktop/gnome/interface/accessibility true
        gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_enable true
        gct -s -t bool /desktop/gnome/accessibility/keyboard/stickykeys_modifier_beep false
        gct -s -t bool /desktop/accessibility/gnome/keyboard/stickykeys_two_key_off false
        gct -s -t list --list-type=string /desktop/gnome/accessibility/startup/exec_ats [onboard]

        kderc_addtoprefixes /usr/share/kubuntu-default-settings/kde-profile/minor-motor-difficulties/,/usr/share/kubuntu-default-settings/kde-profile/motor-difficulties-pointing-devices/
        ;;
esac

log_end_msg
