#! /bin/sh

PREREQ=""
DESCRIPTION="Configuring some drivers..."

. /scripts/functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

if [ -e /root/etc/default/linux-restricted-modules-common ]; then
	echo 'DISABLED_MODULES="fglrx nv"' >> /root/etc/default/linux-restricted-modules-common
fi
