#! /bin/sh

PREREQ=""
DESCRIPTION="Disabling kwallet..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

rm -f /root/usr/share/services/kded/kwalletd.desktop

log_end_msg