#! /bin/sh

PREREQ=""
DESCRIPTION="Fixing language selector..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

if [ -e /root/usr/share/applications/language-selector.desktop ]; then
    sed -i '/^Exec/ s|/usr/bin/gnome-language-selector|"& -n"|' /root/usr/share/applications/language-selector.desktop

fi

if [ -x /root/usr/bin/fontconfig-voodoo ]; then
    chroot /root fontconfig-voodoo --auto --quiet || true
fi

log_end_msg
