#! /bin/sh

PREREQ=""
DESCRIPTION="Adding APT-CDROM source..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

mkdir -p /root/cdrom
mount -n -o bind /cdrom /root/cdrom
chroot /root apt-cdrom -m add
umount /root/cdrom
