#!/bin/sh
# live-initramfs helper functions, used by live-initramfs on boot and by live-snapshot

if [ ! -x "/bin/fstype" ]
then
	# klibc not in path -> not in initramfs
	export PATH="${PATH}:/usr/lib/klibc/bin"
fi

sys2dev ()
{
	sysdev=${1#/sys}
	echo "/dev/$(udevinfo -q name -p ${sysdev} 2>/dev/null|| echo ${sysdev##*/})"
}

subdevices ()
{
	sysblock=${1}
	r=""

	for dev in "${sysblock}" "${sysblock}"/*
	do
		if [ -e "${dev}/dev" ]
		then
			r="${r} ${dev}"
		fi
	done

	echo ${r}
}

is_supported_fs ()
{
	# FIXME: do something better like the scan of supported filesystems
	fstype="${1}"

	case ${fstype} in
		vfat|iso9660|udf|ext2|ext3|ntfs|jffs2)
		return 0
		;;
	esac

	return 1
}

get_fstype ()
{
	local FSTYPE
	local FSSIZE

	# fstype misreports LUKS devices
	if is_luks "${1}"
	then
	    /lib/udev/vol_id -t ${1} 2>/dev/null
	    return
	fi

	eval $(fstype < ${1})

	if [ "${FSTYPE}" != "unknown" ]
	then
		echo ${FSTYPE}
		return 0
	fi

	/lib/udev/vol_id -t ${1} 2>/dev/null
}

where_is_mounted ()
{
	device=${1}

	if grep -q "^${device} " /proc/mounts
	then
		# return the first found
		grep "^${device} " /proc/mounts | cut -f2 -d ' '
	fi
}

lastline ()
{
	while read lines
	do
		line=${lines}
	done

	echo "${line}"
}

base_path ()
{
	testpath="${1}"
	mounts="$(awk '{print $2}' /proc/mounts)"
	testpath="$(busybox realpath ${testpath})"

	while true
	do
		if echo "${mounts}" | grep -qs "^${testpath}"
		then
			set -- $(echo "${mounts}" | grep "^${testpath}" | lastline)
			echo ${1}
			break
		else
			testpath=$(dirname $testpath)
		fi
	done
}

fs_size ()
{
	# Returns used/free fs kbytes + 5% more
	# You could pass a block device as ${1} or the mount point as ${2}

	dev="${1}"
	mountp="${2}"
	used="${3}"

	if [ -z "${mountp}" ]
	then
		mountp="$(where_is_mounted ${dev})"

		if [ -z "${mountp}" ]
		then
			mountp="/mnt/tmp_fs_size"

			mkdir -p "${mountp}"
			mount -t $(get_fstype "${dev}") -o ro "${dev}" "${mountp}"

			doumount=1
		fi
	fi

	if [ "${used}" = "used" ]
	then
		size=$(du -ks ${mountp} | cut -f1)
		size=$(expr ${size} + ${size} / 20 ) # FIXME: 5% more to be sure
	else
		# free space
		size="$(df -k | grep -s ${mountp} | awk '{print $4}')"
	fi

	if [ -n "${doumount}" ]
	then
		umount "${mountp}"
		rmdir "${mountp}"
	fi

	echo "${size}"
}

load_keymap ()
{
	# Load custom keymap
	if [ -x /bin/loadkeys -a -r /etc/boottime.kmap.gz ]
	then
		loadkeys /etc/boottime.kmap.gz
	fi
}

setup_loop ()
{
	local fspath=${1}
	local module=${2}
	local pattern=${3}
	local offset=${4}
	local encryption=${5}
	local readonly=${6}

	modprobe -q -b "${module}"
	udevsettle

	for loopdev in ${pattern}
	do
		if [ "$(cat ${loopdev}/size)" -eq 0 ]
		then
			dev=$(sys2dev "${loopdev}")
			options=''

			if [ -n ${readonly} ]
			then
				if /sbin/losetup --help 2>&1 | grep -q -- "-r\b"
				then
					options="${options} -r"
				fi
			fi

			if [ 0 -lt "${offset}" ]
			then
				options="${options} -o ${offset}"
			fi

			if [ -z "${encryption}" ]
			then
				losetup ${options} "${dev}" "${fspath}"
			else
				# Loop AES encryption
				while true
				do
					load_keymap

					echo -n "Enter passphrase for root filesystem: " >&6
					read -s passphrase
					echo "${passphrase}" > /tmp/passphrase
					unset passphrase
					exec 9</tmp/passphrase
					/sbin/losetup ${options} -e "${encryption}" -p 9 "${dev}" "${fspath}"
					error=${?}
					exec 9<&-
					rm -f /tmp/passphrase

					if [ 0 -eq ${error} ]
					then
						unset error
						break
					fi

					echo
					echo -n "There was an error decrypting the root filesystem ... Retry? [Y/n] " >&6
					read answer

					if [ "$(echo "${answer}" | cut -b1 | tr A-Z a-z)" = "n" ]
					then
						unset answer
						break
					fi
				done
			fi

			echo "${dev}"
			return 0
		fi
	done

	panic "No loop devices available"
}

try_mount ()
{
	dev="${1}"
	mountp="${2}"
	opts="${3}"

	old_mountp="$(where_is_mounted ${dev})"

	if [ -n "${old_mountp}" ]
	then
		mount -o remount,"${opts}" "${dev}" "${old_mountp}" || panic "Remounting ${dev} ${opts} on ${old_mountp} failed"
		mount -o bind "${old_mountp}" "${mountp}" || panic "Cannot bind-mount ${old_mountp} on ${mountp}"
	else
		mount -t $(get_fstype "${dev}") -o "${opts}" "${dev}" "${mountp}" || panic "Cannot mount ${dev} on ${mountp}"
	fi
}

find_cow_device ()
{
	pers_label="${1}"
	cow_backing="/${pers_label}-backing"

	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v fd)
	do
		for dev in $(subdevices "${sysblock}")
		do
			devname=$(sys2dev "${dev}")

			if [ "$(/lib/udev/vol_id -l ${devname} 2>/dev/null)" = "${pers_label}" ]
			then
				echo "${devname}"
				return
			fi

			case "$(get_fstype ${devname})" in
				vfat|ext2|ext3|jffs2)
					mkdir -p "${cow_backing}"
					try_mount "${devname}" "${cow_backing}" "rw"

					if [ -f "${cow_backing}/${pers_label}" ]
					then
						echo $(setup_loop "${cow_backing}/${pers_label}" "loop" "/sys/block/loop*")
						return 0
					else
						umount ${cow_backing}
					fi
					;;
				*)
					;;
			esac
		done
	done
}

find_files ()
{
	# return the first of ${filenames} found on vfat and ext2/ext3 devices
	# FIXME: merge with above function

	filenames="${1}"
	snap_backing="/snap-backing"

	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v fd)
	do
		for dev in $(subdevices "${sysblock}")
		do
			devname=$(sys2dev "${dev}")
			devfstype="$(get_fstype ${devname})"

			if is_supported_fs ${devfstype}
			then
				mkdir -p "${snap_backing}"
				try_mount "${devname}" "${snap_backing}" "ro"

				for filename in ${filenames}
					do
					if [ -f "${snap_backing}/${filename}" ]
					then
						echo "${devname} ${snap_backing} ${filename}"
						return 0
					fi
				done

				umount ${snap_backing}
			fi
		done
	done
}

get_mac ()
{
	mac=""

	for adaptor in /sys/class/net/*
	do
		status="$(cat ${adaptor}/iflink)"

		if [ "${status}" -eq 2 ]
		then
			mac="$(cat ${adaptor}/address)"
			mac="$(echo ${mac} | sed 's/:/-/g' | tr '[a-z]' '[A-Z]')"
		fi
	done

	echo ${mac}
}

is_luks()
{
    devname="${1}"
    if [ -x /sbin/cryptsetup ]
    then
	/sbin/cryptsetup isLuks "${devname}" 2>/dev/null || ret=${?}
	return ${ret}
    else
	return 1
    fi

}
